### ISSUE TITLE
Scraping und Parserklasse für HWR Kalender

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#102]
Wir brauchen für das regelmäßige Scraping (Checken definierter URLs nach Inhalten, Inhaltsänderungen), sowie für die Verarbeiten dieser Inhalte (Parsing) jeweils (mind.) eine Klasse. D.h. zu diesem EPIC sollten jeweils verlinkte Subissues angelegt werden und hier als ToDos rein.

- [x] Issue 1 : erkennen der Eingetragenen Inhalte (z.B. VWL Wagner)
- [x] Issue 2 : Zuordnung der erkannten Daten (Zeitraum, Datum)
- [x] Issue 3 : Auslesen der Daten
- [x] Issue 4 : Ausgabe der Daten im Projektkalender
usw.

Die URLs sind folgendermaßen aufgebaut:
https://moodle.hwr-berlin.de/fb2-stundenplan/fb2-stundenplaene/wi/semester2/kursc.html
Source Code:
view-source:https://moodle.hwr-berlin.de/fb2-stundenplan/fb2-stundenplaene/wi/semester2/kursc.html

Da dies auch für andere Studiengänge und Kurse gilt, können wir den Kalender theoretisch entsprechend erweitern (Konfig des Kurses in den Settings). Wird aber auch so erstmal genug Arbeit, da die HTML  ziemlich chaotisch ist...

**Comment by HansenBerlin** [comment]
s. auch Comment in Teams und betreffend #103 und #104 ihr könnt euch das mal angucken: https://ical4j.github.io/ical4j-user-guide/examples/ Denke da ist die Umwandlung in unsere Formate einfacher als bei biweekly, zumal letzteres sehr alt zu sein scheint.
