### ISSUE TITLE
Implementierung der Views in die View Controller

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#157]
relates to #94 #156 
Wenn die Views erstellt sind (die entsprechenden Controllerklassen sind es schon, aber bis auf die geerbten un implementierten Methoden noch leer) müssen die verwendeten Elemente (Nodes) mit ihren Ids und @FXML Decorator in den jeweiligen Klassen angelegt werden. Jeder ViewController hat seine eigene Logik für die Kommunikation mit anderen high Level Controllern die hier jeweils implementiert werden muss. 
Die Controller werden nicht i der FXML File (aka im Scenebuilder) zugewiesen, da dies dynamisch zur Laufzeit geschieht.
Die notwendigen Objekte werden per DI übergeben, müssen also nicht nochmal gebaut werden, sagt wenn hier was fehlt bzw. guckt euch die Architektur selbst an und baut es dann ein (Ausgangspunkt MainJFX, hier werden alle Objekte gebaut bzw. das wird später noch in ne Factory ausgelagert). 
Da dies die Grundlage für den "Zusammenbau" mit den Highlevel Controllerklassen ist, sollten wir dies m.E. mit Priorität behandeln, zumindest für Planer, Search und Settings. Also: je ViewControllerklasse sollte folgendes sichergestellt sein:

- [x] alle Nodes, mit denen interagiert wird oder deren Werte wir brauchen haben eine ID in der FXML und das jeweilige Objekt ist im Controller deklariert.
- [x] Event Methoden sind implementiert und werden von den Nodes registriert
- [x] der Controller ist NICHT in der fxml verlinkt
- [x] alle Vorgänge die die Kommunikation zwischen UI und Geschäftslogik/Models betreffen, werden vom View Controller gesteuert, außer Eingabevalidierung, Eventbehandlung o.ä. macht dieser aber selber keine weiteren "schlauen" Sachen
- [x] Wenn es Elemente gibt, die bei Veränderung der Fenstergröße aus dem Bild rutschen, muss deren Position in den dafür bereits implementierten Methode angepasst werden (Verschiebung im Grid)
- [x] in den Methoden des Controllers werden keine individuellen Objekte gebaut (Vanilla Java ist ok)

Kriterien erfüllt für

- [x] Planer ViewController
- [x] Search ViewController
- [x] Stats ViewController (keine prio)
- [x] Settings ViewController
- [x] MailTemplate ViewController
- [x] Contacts ViewController
