### ISSUE TITLE
Set up Continous Delivery Pipeline

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#93]
- [x] Integration Maven und Update des Repos
- [x] GitHub Actions für Build und JUnit
- [x] Statische Analyse (Research Tool und Integration)
- [x] GitHub Actions für Deployment in GutHub Packages
- [x] Update Github Page in release
