### ISSUE TITLE
Erstellung FXML/ GUI

### ISSUE THREAD

**Issue by GrandpaNeubert** [HansenBerlin/altenheim-kalender#94]
- [x] #73 Design_I
- [x] CalenderFX implementieren
- [x] Google Material Design implementieren --> not valid, haben uns für metro (aus JMetro, analog Win10) entschieden
- [x] Entwürfe für Mainpage und Subpages
- [x] Entscheidung für 2 Farbpattern (light und dark)
- [x] CSS vorbereiten
- [x] Implementierung
- [x] Check können mehrere FXML Files in einer Stage geladen werden #119 
- [x] #126 
- [x] #125 
- [x] alle Userstories beachten
- [x] Erstellung MainView .fxml File
- [x] "" Planer View
- [x] "" SearchView
- [x] "" Kontakte View
- [x] "" SettingsView
- [x] "" Stats View (evtl., low prio) - nicht in diesem Release
- [x] "" Popup neuer Eintrag

**Comment by HansenBerlin** [comment]
Habe für die UI mal das probiert:
https://github.com/palexdev/MaterialFX
Ist ganz ok, viel Auswahl für JFX gibts halt auch nicht. Performanceimpact müssen wir mal noch checken, es wirkt langsam, kann aber auch FX generell liegen.
